version = 0.1

[default.deploy.parameters]
stack_name = "deerdash-backend"
resolve_s3 = true
s3_prefix = "deerdash-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
